### PR TITLE
Sbt processor

### PR DESCRIPTION
**Pull request by apeshimam**
Hey Wille,

I wanted to create a pull to see what you thought of the blank project processor. And I'd like to close this one out and then get working on additional ones.

Thanks!
a

### CODE REVIEW

**Comment by wfaler** [comment]
Thanks, I'll have a look at it in a couple of days - unfortunately I'm completely snowed under at the moment (among other things, investigating breakages with 2.9.RC1)

**Comment by wfaler** [comment]
Still has a few rough edges, but a promising start nonetheless!

**Comment by apeshimam** [comment]
Awesome. Let me know if you have any specific feedback.

**Comment by wfaler** [comment]
Hi,
One of those weeks.. 
An obvious first thing is that the templates and web.xml should stay in sync with the default package chosen by the user - so for instance if the user chooses a package of "com.myco", the classes will be in the right package, and the web.xml will refer to the right package.

**Comment by apeshimam** [comment]
:) definitely understand about the busy-ness. Im submitting a pull to address this issue.

**Comment by wfaler** [comment]
..and some unit-tests around the individual classes would be nice too.. :)

We'll probably want to expand on the functionality on the processor soon enough, so it would be nice to have solid ground to stand on to ensure we don't create issues or regress ones we fix.

**Pull request merged**
