### PR TITLE
Addresses web.xml package name issue as well as renames the processor.

### PR DESCRIPTION
**Pull request by apeshimam**

### CODE REVIEW

**Comment by wfaler** [comment]
Thanks! 
Any possibility of some tests around it?

**Comment by apeshimam** [comment]
Yep. I'll get working on that in the next day or so .

**Comment by wfaler** [comment]
Great!

After that, if you want to continue with the processor, I can start specing up some ideas of features that may be nice to have.
How would you prefer to manage that if you want to go ahead? Maybe one way is to simply raise them as Github "issues" on your fork so you effectively "own" the improvements?

**Comment by apeshimam** [comment]
Hey Wille, 

So, Im actually struggling a little bit with defining a set of test cases. The lifty engine is implemented quite well so what's left is essentially definition of the templates and their outputs. As a result, I dont see much value in unit testing. It might be possible to implement some full integration tests, but Id have to dig into how to accomplish that. Can you take a look at the processor and then let me know if you can figure a way to implement useful test cases.

thanks
a

**Comment by wfaler** [comment]
Hi,
I don't think a massive amount of testing is needed, however some "quasi" integration/unit-tests maybe, just adding checking that files are put in the right packages/folders for user input, that the generated sources refer to the right package etc.

Basically ensure that where there is user-input, it turns up in the right place, so we don't miss anything like for instance the web.xml reference you fixed before.

**Pull request merged**
